<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AssemblyName>checkpointchaliescruisemissile</AssemblyName>
    <Version>1.4.1</Version>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>latest</LangVersion>
    <NoWarn>$(NoWarn);MSB3277</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BepInEx.Analyzers" Version="1.*" PrivateAssets="all" />
    <PackageReference Include="BepInEx.Core" Version="5.*" />
    <PackageReference Include="BepInEx.PluginInfoProps" Version="1.*" />
    <PackageReference Include="UnityEngine.Modules" Version="2021.3.33" IncludeAssets="compile" />
    <PackageReference Include="stafelstr.nonuget" Version="1.1.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="AlteredDestination.Tests/**/*.cs" />
    <None Include="AlteredDestination.Tests/**/*.cs" />
  </ItemGroup>

</Project>
