# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  workflow_dispatch: {}
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

permissions:
  contents: read

jobs:
  build:

    runs-on: docker

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore AlteredDestination.Tests/AlteredDestination.Tests.csproj
    - name: Build
      run: dotnet build AlteredDestination.csproj --no-restore
    - name: Test
      run: dotnet test AlteredDestination.Tests/AlteredDestination.Tests.csproj --no-restore --verbosity normal
